name: Automatic deployment ✨

on:

  # Trigger workflow when pushing to "dev"
  push:
    branches:
      - dev

  # Add manual triggers too
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      #
      # Checkout source code
      #
      - name: Checkout source code
        uses: actions/checkout@v4

      #
      # Setup Node JS
      #
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      #
      # Install dependencies
      #
      - name: Install dependencies
        run: npm ci

      #
      # Build
      #
      - name: Build code
        run: npm run build -- --configuration production

      #
      # Deploy to VPS
      #
      - name: Deploy to VPS
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.VPS_HOST }}
          REMOTE_USER: ${{ secrets.VPS_USER }}
          SOURCE: "dist/kuv-client/browser/"
          TARGET: "/var/www/kuv-client"
          ARGS: "-rlgoDzP --delete"

      #
      # Notify about deploy in discord
      #
      - name: Send Discord Notification
        if: always()
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ vars.DISCORD_FRONT_WEBHOOK }}
          title: "🚀 Ready"
          description: "KuV client is now deployed"
          color: 3066993
